version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.12.12
    environment:
      - EDGE_PORT=4584
      - SERVICES=secretsmanager,lambda
      - DEFAULT_REGION=eu-north-1 # Required for awslocal to seed to correct regions
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=localstack-network
      - LAMBDA_CONTAINER_REGISTRY=mlupin/docker-lambda
      - AWS_ACCESS_KEY_ID=xxx # Required for other services (e.g. Rates API) to get credentials
      - AWS_SECRET_ACCESS_KEY=xxx
    volumes:
      - ./content/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
      - ./content/setup:/setup
      - /var/run/docker.sock:/var/run/docker.sock # Required for Lambda execution
    ports:
      - 4584:4584
    networks:
      - localstack-network

networks:
  localstack-network:
    name: localstack-network # Explicitly define network name to stop docker-compose automatically adding a prefix - we need it explicit so we can reference it
    driver: bridge
